'use strict';
const {allows}=require('./team_access');const {validZone}=require('./booking_settings');const {localTime,bookingPrice}=require('./booking_quote');
const id=v=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,128}$/.test(v),revision=d=>`${d.updateTime.seconds}:${d.updateTime.nanoseconds}`;
function createBookingWorkspaceHandler({db,Timestamp,HttpsError,calendar}){const fail=(code,key='booking_'+code)=>{throw new HttpsError(code,key);};return async request=>{
 const d=request.data||{},uid=request.auth?.uid;if(!uid)fail('unauthenticated');
 const identity=['action','organizationId','buildingId'];let extra=[];
 if(d.action==='list')extra=['cursor'];else if(d.action==='read')extra=['bookingId'];else if(d.action==='quote')extra=['roomId','startLocal','endLocal','occurrence','pricingType','overrideMinor','overrideReason'];else if(d.action==='save')extra=['bookingId','operationId','revision','roomId','roomRevision','startLocal','endLocal','occurrence','pricingType','guestName','guestPhone','notes','depositMinor','overrideMinor','overrideReason'];else if(d.action==='command')extra=['bookingId','operationId','revision','command','amountMinor','paymentMethod','status','reason'];else if(d.action!=='rooms')fail('invalid-argument');
 if(!id(d.organizationId)||!id(d.buildingId)||Object.keys(d).some(k=>![...identity,...extra].includes(k)))fail('invalid-argument');
 const prepared=await db.runTransaction(async tx=>{
 const org=await tx.get(db.doc(`organizations/${d.organizationId}`)),member=await tx.get(db.doc(`memberships/${uid}_${d.organizationId}`)),m=member.data(),scope={organizationId:d.organizationId,userId:uid,buildingId:d.buildingId};if(!org.exists||org.data().accessVersion!==2||!allows(m,'readBookings',scope))fail('permission-denied');
 const building=await tx.get(db.doc(`buildings/${d.buildingId}`)),b=building.data();if(!b||b.organizationId!==d.organizationId)fail('not-found');const zone=b.timeZone;if(!validZone(zone))fail('failed-precondition','lease_property_timezone_required');
 if(d.action==='rooms'){const rows=await tx.get(db.collection('rooms').where('organizationId','==',d.organizationId).where('buildingId','==',d.buildingId));return {canPrice:allows(m,'overridePrices',scope),records:rows.docs.filter(v=>['hourly','both'].includes(v.data().rentalMode)).map(v=>({id:v.id,roomNumber:v.data().roomNumber??v.id,currency:v.data().currency??'VND'})),timeZone:zone};}
 const projection=doc=>{const x=doc.data(),iso=v=>v?.toDate?.().toISOString()??null;const local=v=>{if(!v?.toDate)return '';const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(v.toDate()).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day} ${p.hour}:${p.minute}`;};return {id:doc.id,revision:revision(doc),roomId:x.roomId,guestName:x.guestName??'',guestPhone:x.guestPhone??'',notes:x.notes??'',status:x.status,startTime:iso(x.startTime),endTime:iso(x.endTime),startLocal:local(x.startTime),endLocal:local(x.endTime),currency:x.currency,totalPrice:x.totalPrice,paidAmount:x.paidAmount,depositAmount:x.depositAmount??0,depositPaidAmount:x.depositPaidAmount??0,depositRefundedAmount:x.depositRefundedAmount??0,pricingType:x.pricingType,timeZone:zone,canManage:allows(m,'manageBookings',scope),canCollect:allows(m,'collectPayments',scope),canRefund:allows(m,'refundPayments',scope)};};
 if(d.action==='list'){if(d.cursor!=null&&!id(d.cursor))fail('invalid-argument');let q=db.collection('bookings').where('organizationId','==',d.organizationId).where('buildingId','==',d.buildingId).orderBy('__name__');if(d.cursor)q=q.startAfter(d.cursor);const page=await tx.get(q.limit(26)),rows=page.docs.slice(0,25);return {records:rows.map(projection),nextCursor:page.size>25?rows.at(-1).id:null,canManage:allows(m,'manageBookings',scope),timeZone:zone};}
 if(['read','command'].includes(d.action)||d.action==='save'&&d.revision!=null){if(!id(d.bookingId))fail('invalid-argument');const doc=await tx.get(db.doc(`bookings/${d.bookingId}`));if(!doc.exists||doc.data().organizationId!==d.organizationId||doc.data().buildingId!==d.buildingId)fail('not-found');if(d.action==='read')return {record:projection(doc)};if(d.action==='save'&&d.roomId!==doc.data().roomId)fail('invalid-argument');}
 if(d.action==='command'){
  if(typeof d.reason!=='string'||!d.reason.trim()||d.reason.length>1000)fail('invalid-argument');
  if(!id(d.operationId)||!['status','payment','deposit','refund','refundRent','checkout'].includes(d.command)||typeof d.revision!=='string')fail('invalid-argument');
  if(['payment','deposit','refund','refundRent'].includes(d.command)&&(!Number.isSafeInteger(d.amountMinor)||d.amountMinor<=0))fail('invalid-argument');
  const doc=await tx.get(db.doc(`bookings/${d.bookingId}`)),currency=doc.data().currency;
  return {command:{action:d.command,bookingId:d.bookingId,operationId:d.operationId,revision:d.revision,...(d.amountMinor!=null?{amount:d.amountMinor/(currency==='USD'?100:1)}:{}),paymentMethod:d.paymentMethod,status:d.status,reason:d.reason}};
 }
 if(!allows(m,'manageBookings',scope)||!id(d.roomId))fail('permission-denied');const room=await tx.get(db.doc(`rooms/${d.roomId}`)),r=room.data();if(!r||r.organizationId!==d.organizationId||r.buildingId!==d.buildingId||!['hourly','both'].includes(r.rentalMode))fail('not-found');
 if(d.overrideMinor!=null&&(!allows(m,'overridePrices',scope)||!Number.isSafeInteger(d.overrideMinor)||d.overrideMinor<=0||d.overrideMinor>1e12||typeof d.overrideReason!=='string'||!d.overrideReason.trim()||d.overrideReason.length>1000))fail('permission-denied');
 const start=localTime(d.startLocal,zone,d.occurrence),end=localTime(d.endLocal,zone,d.occurrence);if(start===null||end===null||!['hourly','daily','overnight'].includes(d.pricingType))fail('invalid-argument','booking_invalid_dates');
 let quote;try{quote=bookingPrice(r,start,end,d.pricingType);}catch(e){fail('failed-precondition',e.message);}
 if(d.overrideMinor!=null)quote.totalMinor=d.overrideMinor;
 if(d.action==='quote')return {record:{...quote,roomRevision:revision(room),startTime:new Date(start).toISOString(),endTime:new Date(end).toISOString(),timeZone:zone}};
 if(!id(d.bookingId)||!id(d.operationId)||!Number.isSafeInteger(d.depositMinor)||d.depositMinor<0||d.depositMinor>1e12)fail('invalid-argument');
 return {command:{action:d.revision==null?'create':'edit',bookingId:d.bookingId,operationId:d.operationId,...(d.revision!=null?{revision:d.revision}:{}),roomRevision:d.roomRevision,propertyRevision:revision(building),serverPricing:d.overrideMinor==null,...(d.overrideMinor!=null?{priceOverrideReason:d.overrideReason}:{}),booking:{...(d.overrideMinor!=null?{totalPrice:d.overrideMinor/(quote.currency==='USD'?100:1)}:{}),organizationId:d.organizationId,roomId:d.roomId,guestName:d.guestName,guestPhone:d.guestPhone,notes:d.notes,pricingType:d.pricingType,startTime:{__timestamp:start},endTime:{__timestamp:end},depositAmount:d.depositMinor/(quote.currency==='USD'?100:1)}}};
 });
 if(prepared.command){const c=prepared.command;if(c.action==='edit'){c.changes=c.booking;delete c.booking;}return calendar(c,{auth:request.auth});}return prepared;
};}
module.exports={createBookingWorkspaceHandler};
