const {createHash}=require('node:crypto');const {allows}=require('./team_access');
const id=v=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,128}$/.test(v);
const fields=['floors','roomPrefix','roomType','roomArea','floorRoomCounts'];
const valid=v=>v&&Object.keys(v).length===fields.length&&Number.isInteger(v.floors)&&v.floors>=1&&v.floors<=200&&typeof v.roomPrefix==='string'&&v.roomPrefix.length<=20&&typeof v.roomType==='string'&&v.roomType.trim()&&v.roomType.length<=160&&typeof v.roomArea==='number'&&Number.isFinite(v.roomArea)&&v.roomArea>0&&v.roomArea<=100000&&Array.isArray(v.floorRoomCounts)&&v.floorRoomCounts.length===v.floors&&v.floorRoomCounts.every(n=>Number.isInteger(n)&&n>=0&&n<=500)&&v.floorRoomCounts.reduce((a,b)=>a+b,0)<=10000;
function createPropertyLayoutHandler({db,Timestamp,HttpsError}){const fail=code=>{throw new HttpsError(code,'property_layout_'+code);};return async request=>{
 const d=request.data||{},uid=request.auth?.uid,write=d.action==='update';if(!uid)fail('unauthenticated');const keys=['action','organizationId','buildingId',...(write?['operationId','revision','layout']:[])];if(!['read','update'].includes(d.action)||!id(d.organizationId)||!id(d.buildingId)||Object.keys(d).some(k=>!keys.includes(k))||(write&&(!id(d.operationId)||typeof d.revision!=='string'||!/^\d+:\d+$/.test(d.revision)||!valid(d.layout))))fail('invalid-argument');
 return db.runTransaction(async tx=>{const org=await tx.get(db.doc(`organizations/${d.organizationId}`)),member=await tx.get(db.doc(`memberships/${uid}_${d.organizationId}`));if(!org.exists||org.data().accessVersion!==2||!allows(member.data(),'manageProperty',{organizationId:d.organizationId,userId:uid,buildingId:d.buildingId}))fail('permission-denied');const ref=db.doc(`buildings/${d.buildingId}`),doc=await tx.get(ref),b=doc.data();if(!b||b.organizationId!==d.organizationId)fail('not-found');const revision=`${doc.updateTime.seconds}:${doc.updateTime.nanoseconds}`,layout={floors:b.floors??1,roomPrefix:b.roomPrefix??'',roomType:b.roomType??'',roomArea:b.roomArea??0,floorRoomCounts:b.floorRoomCounts??Array(b.floors??1).fill(0)};
 if(!write)return {record:{name:b.name??'',revision,layout}};const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),key=hash(['propertyLayout',d.organizationId,uid,d.operationId]),op=db.doc(`propertyLayoutOperations/${key}`),prior=await tx.get(op),fingerprint=hash(keys.map(k=>d[k]));if(prior.exists){if(prior.data().fingerprint!==fingerprint)fail('failed-precondition');return prior.data().result;}if(d.revision!==revision)fail('aborted');const now=Timestamp.now(),result={buildingId:d.buildingId};tx.update(ref,{...d.layout,roomType:d.layout.roomType.trim(),updatedAt:now,updatedBy:uid});tx.create(op,{organizationId:d.organizationId,actorId:uid,createdAt:now,fingerprint,result,before:layout,after:d.layout});tx.create(db.doc(`teamActivity/${key}`),{organizationId:d.organizationId,actorId:uid,createdAt:now,action:'property_layout_updated',targetId:d.buildingId,before:layout,after:d.layout});return result;});};}
module.exports={createPropertyLayoutHandler,validLayout:valid};
