import 'dart:io';

import 'package:apartment_management_project_2/models/organization_model.dart';
import 'package:apartment_management_project_2/models/payment_model.dart';
import 'package:apartment_management_project_2/utils/app_localizations.dart';
import 'package:country_flags/country_flags.dart';
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as p;
import 'package:syncfusion_flutter_xlsio/xlsio.dart' as xlsio;

enum ExportLanguage { vi, en, bilingual }

// ─────────────────────────────────────────────────────────────────────────────
// Internal data class — one row in the Excel line-items table
// ─────────────────────────────────────────────────────────────────────────────
class _XlsLineItem {
  final String typeLabel;
  final double amount;
  final String? detail; // meter readings / billing period / notes

  const _XlsLineItem({
    required this.typeLabel,
    required this.amount,
    this.detail,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────
class PaymentExcelExporter {
  PaymentExcelExporter._();

  // ========================================
  // LOCALIZATION HELPERS
  // ========================================
  static String _l(String key, ExportLanguage? lang) {
    final activeLang = lang?.name ?? 'bilingual';
    const labels = {
      // Dialogs & Messages
      'loading': {'vi': 'Đang xuất Excel...', 'en': 'Exporting Excel...', 'bilingual': 'Đang xuất Excel / Exporting...'},
      'error_msg': {'vi': 'Lỗi xuất Excel:', 'en': 'Excel Export Error:', 'bilingual': 'Lỗi / Error:'},
      'save_success': {'vi': 'Đã lưu:', 'en': 'Saved:', 'bilingual': 'Đã lưu / Saved:'},
      'create_success': {'vi': 'Đã tạo file Excel thành công', 'en': 'Excel file created successfully', 'bilingual': 'Thành công / Success'},

      // Main Headers
      'sheet_name': {'vi': 'Hóa Đơn', 'en': 'Invoice', 'bilingual': 'Hóa Đơn / Invoice'},
      'invoice_title': {'vi': 'HÓA ĐƠN THANH TOÁN', 'en': 'PAYMENT INVOICE', 'bilingual': 'HÓA ĐƠN THANH TOÁN / PAYMENT INVOICE'},
      'info_section': {'vi': 'THÔNG TIN HÓA ĐƠN', 'en': 'INVOICE INFO', 'bilingual': 'THÔNG TIN HÓA ĐƠN / INVOICE INFO'},
      'detail_section': {'vi': 'CHI TIẾT CÁC KHOẢN', 'en': 'LINE ITEM DETAILS', 'bilingual': 'CHI TIẾT CÁC KHOẢN / DETAILS'},
      'payment_status_section': {'vi': 'TÌNH TRẠNG THANH TOÁN', 'en': 'PAYMENT STATUS', 'bilingual': 'TÌNH TRẠNG / STATUS'},
      'remark_section': {'vi': 'GHI CHÚ', 'en': 'REMARK', 'bilingual': 'GHI CHÚ / REMARK'},

      // Row Labels
      'inv_id': {'vi': 'Mã hóa đơn:', 'en': 'Invoice ID:', 'bilingual': 'Mã hóa đơn / ID:'},
      'tenant': {'vi': 'Người thuê:', 'en': 'Tenant:', 'bilingual': 'Người thuê / Tenant:'},
      'room': {'vi': 'Phòng:', 'en': 'Room:', 'bilingual': 'Phòng / Room:'},
      'building': {'vi': 'Tòa nhà:', 'en': 'Building:', 'bilingual': 'Tòa nhà / Building:'},
      'email': {'vi': 'Email:', 'en': 'Email:', 'bilingual': 'Email:'},
      'status': {'vi': 'Trạng thái:', 'en': 'Status:', 'bilingual': 'Trạng thái / Status:'},
      'due_date': {'vi': 'Hạn thanh toán:', 'en': 'Due Date:', 'bilingual': 'Hạn thanh toán / Due Date:'},
      'paid_date': {'vi': 'Ngày thanh toán:', 'en': 'Paid Date:', 'bilingual': 'Ngày thanh toán / Paid Date:'},
      'export_date': {'vi': 'Ngày xuất:', 'en': 'Exported:', 'bilingual': 'Ngày xuất / Exported:'},
      
      // Table Columns
      'col_type': {'vi': 'Loại khoản', 'en': 'Type', 'bilingual': 'Loại khoản / Type'},
      'col_note': {'vi': 'Chi tiết / Ghi chú', 'en': 'Details / Notes', 'bilingual': 'Chi tiết / Notes'},
      'col_price': {'vi': 'Số tiền (VND)', 'en': 'Amount (VND)', 'bilingual': 'Số tiền / Amount'},
      
      // Calculation Labels
      'total_items': {'vi': 'Tổng các khoản:', 'en': 'Subtotal:', 'bilingual': 'Tổng các khoản / Subtotal:'},
      'late_fee': {'vi': 'Phí trễ hạn:', 'en': 'Late Fee:', 'bilingual': 'Phí trễ hạn / Late Fee:'},
      'plus': {'vi': 'Cộng:', 'en': 'Plus:', 'bilingual': 'Cộng / Plus:'},
      'tax': {'vi': 'Tiền thuế:', 'en': 'Tax:', 'bilingual': 'Tiền thuế / Tax:'},
      'grand_total': {'vi': 'TỔNG THANH TOÁN:', 'en': 'TOTAL PAYMENT:', 'bilingual': 'TỔNG THANH TOÁN / TOTAL PAYMENT:'},
      'paid_amount': {'vi': 'Đã thanh toán:', 'en': 'Paid Amount:', 'bilingual': 'Đã thanh toán / Paid:'},
      'remaining': {'vi': 'Còn lại:', 'en': 'Remaining:', 'bilingual': 'Còn lại / Remaining:'},
      
      'footer_msg': {'vi': 'Xuất bởi hệ thống quản lý căn hộ', 'en': 'Generated by Apartment Management System', 'bilingual': 'Generated by Apartment Management System'},
      
      // Types
      'rent': {'vi': 'Tiền thuê', 'en': 'Rent', 'bilingual': 'Tiền thuê / Rent'},
      'electricity': {'vi': 'Tiền điện', 'en': 'Electricity', 'bilingual': 'Tiền điện / Electricity'},
      'water': {'vi': 'Tiền nước', 'en': 'Water', 'bilingual': 'Tiền nước / Water'},
      'internet': {'vi': 'Tiền internet', 'en': 'Internet', 'bilingual': 'Tiền internet / Internet'},
      'parking': {'vi': 'Tiền gửi xe', 'en': 'Parking', 'bilingual': 'Tiền gửi xe / Parking'},
      'maintenance': {'vi': 'Phí bảo trì', 'en': 'Maintenance', 'bilingual': 'Phí bảo trì / Maintenance'},
      'deposit': {'vi': 'Tiền cọc', 'en': 'Deposit', 'bilingual': 'Tiền cọc / Deposit'},
      'penalty': {'vi': 'Tiền phạt', 'en': 'Penalty', 'bilingual': 'Tiền phạt / Penalty'},
      'other': {'vi': 'Khác', 'en': 'Other', 'bilingual': 'Khác / Other'},
      'meter_reading': {'vi': 'Chỉ số:', 'en': 'Reading:', 'bilingual': 'Chỉ số / Reading:'},
      'billing_cycle': {'vi': 'Kỳ:', 'en': 'Period:', 'bilingual': 'Kỳ / Period:'},
    };
    return labels[key]?[activeLang] ?? labels[key]?['bilingual'] ?? key;
  }

   // Helper to translate status (since getStatusDisplayName is usually hardcoded)
  static String _lStatus(PaymentStatus status, ExportLanguage lang) {
    final Map<PaymentStatus, Map<String, String>> statusMap = {
      PaymentStatus.pending: {'vi': 'Chưa thanh toán', 'en': 'Unpaid', 'bilingual': 'Chưa thanh toán / Unpaid'},
      PaymentStatus.paid: {'vi': 'Đã thanh toán', 'en': 'Paid', 'bilingual': 'Đã thanh toán / Paid'},
      PaymentStatus.partial: {'vi': 'Thanh toán một phần', 'en': 'Partially Paid', 'bilingual': 'Một phần / Partial'},
      PaymentStatus.overdue: {'vi': 'Quá hạn', 'en': 'Overdue', 'bilingual': 'Quá hạn / Overdue'},
    };
    return statusMap[status]?[lang.name] ?? statusMap[status]?['bilingual'] ?? status.name;
  }

   static Future<ExportLanguage?> _showLanguageDialog(BuildContext context) async {
    ExportLanguage? selected = ExportLanguage.vi;
    final t = AppTranslations.of(context);

    return await showDialog<ExportLanguage>(
      context: context,
      builder: (ctx) {
        return StatefulBuilder(
          builder: (ctx, setState) {
            Widget buildOption({
              required ExportLanguage value,
              required Widget flag,
              required String title,
              required String subtitle,
            }) {
              final isSelected = selected == value;
              return GestureDetector(
                onTap: () => setState(() => selected = value),
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 150),
                  padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(
                      color: isSelected
                          ? Theme.of(ctx).colorScheme.primary
                          : Colors.grey.shade300,
                      width: isSelected ? 2.0 : 0.5,
                    ),
                    color: isSelected
                        ? Theme.of(ctx).colorScheme.primary.withOpacity(0.07)
                        : Colors.transparent,
                  ),
                  child: Row(
                    children: [
                      flag,
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(title,
                                style: const TextStyle(
                                    fontSize: 14, fontWeight: FontWeight.w500)),
                            Text(subtitle,
                                style: TextStyle(
                                    fontSize: 12, color: Colors.grey.shade600)),
                          ],
                        ),
                      ),
                      AnimatedContainer(
                        duration: const Duration(milliseconds: 150),
                        width: 20,
                        height: 20,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: isSelected
                              ? Theme.of(ctx).colorScheme.primary
                              : Colors.transparent,
                          border: Border.all(
                            color: isSelected
                                ? Theme.of(ctx).colorScheme.primary
                                : Colors.grey.shade400,
                            width: 1.5,
                          ),
                        ),
                        child: isSelected
                            ? const Icon(Icons.check, size: 12, color: Colors.white)
                            : null,
                      ),
                    ],
                  ),
                ),
              );
            }

            return AlertDialog(
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
              titlePadding: const EdgeInsets.fromLTRB(20, 20, 20, 4),
              contentPadding: const EdgeInsets.fromLTRB(12, 8, 12, 4),
              actionsPadding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
              title: Row(
                children: [
                  Container(
                    width: 42,
                    height: 42,
                    decoration: BoxDecoration(
                      color: Theme.of(ctx).colorScheme.primary.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Icon(
                      Icons.translate_rounded,
                      color: Theme.of(ctx).colorScheme.primary,
                      size: 22,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          t['export_lang_dialog_subtitle'],
                          style: TextStyle(
                              fontSize: 11,
                              color: Colors.grey.shade500,
                              fontWeight: FontWeight.w400),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          t['export_lang_dialog_title'],
                          style: const TextStyle(
                              fontSize: 18, fontWeight: FontWeight.w600),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              content: SizedBox(
                width: 320,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    buildOption(
                      value: ExportLanguage.vi,
                      flag: CountryFlag.fromCountryCode(
                        'VN',
                        theme: const ImageTheme(
                          width: 48,
                          height: 32,
                          shape: RoundedRectangle(6),
                        ),
                      ),
                      title: t['export_lang_vi_title'],
                      subtitle: t['export_lang_vi_subtitle'],
                    ),
                    const SizedBox(height: 8),
                    buildOption(
                      value: ExportLanguage.en,
                      flag: CountryFlag.fromCountryCode(
                        'US',
                        theme: const ImageTheme(
                          width: 48,
                          height: 32,
                          shape: RoundedRectangle(6),
                        ),
                      ),
                      title: t['export_lang_en_title'],
                      subtitle: t['export_lang_en_subtitle'],
                    ),
                    const SizedBox(height: 8),
                    buildOption(
                      value: ExportLanguage.bilingual,
                      flag: SizedBox(
                        width: 48,
                        height: 36,
                        child: Stack(
                          children: [
                            Positioned(
                              top: 0,
                              left: 0,
                              child: CountryFlag.fromCountryCode(
                                'VN',
                                theme: const ImageTheme(
                                  width: 36,
                                  height: 24,
                                  shape: RoundedRectangle(4),
                                ),
                              ),
                            ),
                            Positioned(
                              bottom: 0,
                              right: 0,
                              child: CountryFlag.fromCountryCode(
                                'US',
                                theme: const ImageTheme(
                                  width: 36,
                                  height: 24,
                                  shape: RoundedRectangle(4),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      title: t['export_lang_bi_title'],
                      subtitle: t['export_lang_bi_subtitle'],
                    ),
                    const SizedBox(height: 8),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.pop(ctx),
                  child: Text(t['cancel']),
                ),
                FilledButton(
                  onPressed: () => Navigator.pop(ctx, selected),
                  child: Text(t['export_lang_btn_export']),
                ),
              ],
            );
          },
        );
      },
    );
  }

  // ── Entry point ─────────────────────────────────────────────────────────────

  /// Builds the workbook, prompts a save-file dialog (Windows) and writes the
  /// file. Shows a [CircularProgressIndicator] while working.
  static Future<void> exportPayment({
    required BuildContext context,
    required Payment payment,
    required Organization organization,
    String? roomNumber,
    String? buildingName,
    String? tenantEmail,
  }) async {
    final lang = await _showLanguageDialog(context);
    if (lang == null || !context.mounted) return;

    // Show spinner
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => const Center(
        child: Card(
          child: Padding(
            padding: EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                CircularProgressIndicator(),
                SizedBox(height: 16),
                Text('Đang xuất Excel…'),
              ],
            ),
          ),
        ),
      ),
    );

    try {
      final bytes = _buildWorkbook(
        language: lang,
        payment: payment,
        organization: organization,
        roomNumber: roomNumber,
        buildingName: buildingName,
        tenantEmail: tenantEmail,
      );

      if (context.mounted) Navigator.of(context).pop(); // close spinner

      final suggestedName =
          'hoa_don_${payment.id}_${DateFormat('yyyyMMdd').format(DateTime.now())}.xlsx';

      if (Platform.isWindows) {
        final location = await getSaveLocation(
          suggestedName: suggestedName,
          acceptedTypeGroups: [
            const XTypeGroup(label: 'Excel', extensions: ['xlsx']),
          ],
        );
        if (location == null) return;

        await File(location.path).writeAsBytes(bytes, flush: true);

        // Open containing folder so user can see the file
        await Process.run(
          'explorer',
          ['/select,', location.path],
          runInShell: true,
        );

        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Đã lưu: ${p.basename(location.path)}'),
              backgroundColor: Colors.green,
            ),
          );
        }
      } else {
        // Android / iOS — use share_plus or a downloads folder as needed.
        // Extend here when mobile support is required.
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Đã tạo file Excel thành công'),
              backgroundColor: Colors.green,
            ),
          );
        }
      }
    } catch (e) {
      if (context.mounted) Navigator.of(context).pop();
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Lỗi xuất Excel: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Workbook builder
  // ─────────────────────────────────────────────────────────────────────────

  static List<int> _buildWorkbook({
    required ExportLanguage language,
    required Payment payment,
    required Organization organization,
    String? roomNumber,
    String? buildingName,
    String? tenantEmail,
  }) {
    final workbook = xlsio.Workbook();
    final sheet = workbook.worksheets[0];
    sheet.name = _l('sheet_name', language);
    sheet.showGridlines = false;

    final df = DateFormat('dd/MM/yyyy');
    final nf = NumberFormat('#,###');
    final now = DateTime.now();

    int row = 1;

    // ── Colour palette ──────────────────────────────────────────────────────
    const cPrimary = '#1565C0';   // deep blue  — header bg
    const cPrimaryFg = '#FFFFFF'; // white text on blue
    const cAccent = '#E3F2FD';    // light blue — section headers
    const cAlt = '#F5F5F5';       // light grey — alternate rows
    const cTotal = '#1B5E20';     // dark green — grand total bg
    const cTotalFg = '#FFFFFF';
    const cLateFee = '#B71C1C';   // dark red   — late fee text
    const cTax = '#E65100';       // dark orange — tax text

    // ── Helper closures ─────────────────────────────────────────────────────

    xlsio.Range r(int ro, int co, [int? re, int? ce]) {
      if (re != null && ce != null) {
        return sheet.getRangeByIndex(ro, co, re, ce);
      }
      return sheet.getRangeByIndex(ro, co);
    }

    void mergeSet(int ro, int co, int re, int ce, {
      String? text,
      double? number,
      bool bold = false,
      double fontSize = 10,
      String? bg,
      String? fg,
      xlsio.HAlignType hAlign = xlsio.HAlignType.left,
      bool wrap = false,
    }) {
      final range = sheet.getRangeByIndex(ro, co, re, ce);
      range.merge();
      if (text != null) range.setText(text);
      if (number != null) range.setNumber(number);
      range.cellStyle.bold = bold;
      range.cellStyle.fontSize = fontSize;
      range.cellStyle.hAlign = hAlign;
      range.cellStyle.wrapText = wrap;
      if (bg != null) range.cellStyle.backColor = bg;
      if (fg != null) range.cellStyle.fontColor = fg;
    }

    void sectionHeader(int ro, String text) {
      mergeSet(ro, 1, ro, 7,
          text: text,
          bold: true,
          fontSize: 11,
          bg: cAccent);
    }

    void labelValue(int ro, String label, String value) {
      r(ro, 1).setText(label);
      r(ro, 1).cellStyle.bold = true;
      r(ro, 1).cellStyle.fontSize = 10;
      mergeSet(ro, 2, ro, 7, text: value, fontSize: 10);
    }

    // ── Document header ──────────────────────────────────────────────────────

    // Org name — large centred title
    mergeSet(row, 1, row, 7,
        text: organization.name,
        bold: true,
        fontSize: 16,
        hAlign: xlsio.HAlignType.center);
    row++;

    // Invoice title banner
    mergeSet(row, 1, row, 7,
        text: _l('invoice_title', language),
        bold: true,
        fontSize: 13,
        bg: cPrimary,
        fg: cPrimaryFg,
        hAlign: xlsio.HAlignType.center);
    row += 2;

    // ── Invoice metadata ─────────────────────────────────────────────────────

    sectionHeader(row, _l('info_section', language));
    row++;
    labelValue(row, _l('inv_id', language), payment.id);
    row++;
    labelValue(row, _l('tenant', language), payment.tenantName ?? 'N/A');
    row++;

    if (roomNumber != null) { labelValue(row, _l('room', language), roomNumber); row++; }
    if (buildingName != null) { labelValue(row, _l('building', language), buildingName); row++; }
    
    if (tenantEmail != null && tenantEmail.isNotEmpty) { labelValue(row, _l('email', language), tenantEmail); row++; }

    labelValue(row, _l('status', language), _lStatus(payment.status, language));
    row++;
    labelValue(row, _l('due_date', language), df.format(payment.dueDate));
    row++;

    if (payment.paidAt != null) { labelValue(row, _l('paid_date', language), df.format(payment.paidAt!)); row++; }

    if (payment.status == PaymentStatus.partial) {
      labelValue(
        row,
        _l('paid_amount', language), // Use the localized key
        '${nf.format(payment.paidAmount)} VND',
      );
      row++;
    }

    labelValue(row, _l('export_date', language), df.format(now));
    row += 2;

    // ── Line items table ─────────────────────────────────────────────────────

    sectionHeader(row, _l('detail_section', language));
    row++;

    // Table column headers
    final headers = ['#', _l('col_type', language), _l('col_note', language), '', '', _l('col_price', language), ''];
    for (int col = 0; col < headers.length; col++) {
      final cell = r(row, col + 1);
      cell.setText(headers[col]);
      cell.cellStyle.bold = true;
      cell.cellStyle.backColor = cPrimary;
      cell.cellStyle.fontColor = cPrimaryFg;
      cell.cellStyle.hAlign = xlsio.HAlignType.center;
    }
    row++;

    final lineItems = _parseLineItems(payment, df, nf, language);

    for (int i = 0; i < lineItems.length; i++) {
      final item = lineItems[i];
      final bg = (i % 2 == 0) ? cAlt : '#FFFFFF';

      // # column
      r(row, 1).setNumber((i + 1).toDouble());
      r(row, 1).cellStyle.hAlign = xlsio.HAlignType.center;
      r(row, 1).cellStyle.backColor = bg;

      // Type label
      r(row, 2).setText(item.typeLabel);
      r(row, 2).cellStyle.bold = true;
      r(row, 2).cellStyle.backColor = bg;

      // Detail (spans 3 columns)
      mergeSet(row, 3, row, 5,
          text: item.detail ?? '',
          bg: bg,
          wrap: true,
          fontSize: 9);

      // Amount (spans 2 columns)
      mergeSet(row, 6, row, 7,
          number: item.amount,
          bg: bg,
          hAlign: xlsio.HAlignType.right);
      sheet.getRangeByIndex(row, 6, row, 7).numberFormat = '#,##0 "₫"';

      row++;
    }

    row++;

    // ── Totals block ─────────────────────────────────────────────────────────

    void summaryRow(
      int ro,
      String label,
      double amount, {
      bool bold = false,
      double fontSize = 10,
      String? labelColor,
      String? bg,
    }) {
      mergeSet(ro, 1, ro, 5, text: label, bold: bold, fontSize: fontSize, fg: labelColor, bg: bg);
      mergeSet(ro, 6, ro, 7,
          number: amount,
          bold: bold,
          fontSize: fontSize,
          fg: labelColor,
          bg: bg,
          hAlign: xlsio.HAlignType.right);
      sheet.getRangeByIndex(ro, 6, ro, 7).numberFormat = '#,##0 "₫"';
    }

    summaryRow(row, _l('total_items', language), payment.amount);
    row++;

    if (payment.lateFee != null && payment.lateFee! > 0) {
      summaryRow(row, _l('late_fee', language), payment.lateFee!, labelColor: cLateFee);
      row++;
    }

    final subTotal = payment.amount + (payment.lateFee ?? 0);
    if ((payment.lateFee ?? 0) > 0) {
      summaryRow(row, _l('plus', language), subTotal);
      row++;
    }

    if (payment.taxAmount != null && payment.taxAmount! > 0) {
      summaryRow(row, _l('tax', language), payment.taxAmount!, labelColor: cTax);
      row++;
    }

    // Grand total — highlighted green
    summaryRow(row, _l('grand_total', language), payment.totalAmount, bold: true, fontSize: 13, bg: cTotal, labelColor: cTotalFg);
    sheet.getRangeByIndex(row, 1, row, 7).cellStyle.fontColor = cTotalFg;
    row += 2;

    // ── Payment status note ─────────────────────────────────────────────────

    if (payment.status == PaymentStatus.partial) {
      sectionHeader(row, _l('payment_status_section', language));
      row++;
      labelValue(row, _l('paid_amount', language), '${nf.format(payment.paidAmount)} VND');
      row++;
      labelValue(row, _l('remaining', language), '${nf.format(payment.totalAmount - payment.paidAmount)} VND');
      row += 2;
    }

    // ── Notes ────────────────────────────────────────────────────────────────

    if (payment.notes != null && payment.notes!.isNotEmpty) {
      sectionHeader(row, _l('remark_section', language));
      row++;
      mergeSet(row, 1, row, 7, text: payment.notes!, wrap: true);
      row++;
    }

    // ── Footer ───────────────────────────────────────────────────────────────
    row++;
    mergeSet(row, 1, row, 7, text: '${_l('footer_msg', language)} • ${df.format(now)}', fontSize: 9, fg: '#9E9E9E', hAlign: xlsio.HAlignType.center);

    // ── Column widths ────────────────────────────────────────────────────────
    //  Col 1: # (narrow)
    //  Col 2: type label
    //  Col 3-5: detail (wide merged)
    //  Col 6-7: amount (merged)
    sheet.setColumnWidthInPixels(1, 28);
    sheet.setColumnWidthInPixels(2, 120);
    sheet.setColumnWidthInPixels(3, 100);
    sheet.setColumnWidthInPixels(4, 100);
    sheet.setColumnWidthInPixels(5, 100);
    sheet.setColumnWidthInPixels(6, 130);
    sheet.setColumnWidthInPixels(7, 10); // spacer

    final bytes = workbook.saveAsStream();
    workbook.dispose();
    return bytes;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Parse payment into _XlsLineItem list — mirrors _parseLineItems in
  // view_edit_dialogs.dart but produces detail strings ready for Excel cells.
  // ─────────────────────────────────────────────────────────────────────────

  static List<_XlsLineItem> _parseLineItems(Payment payment, DateFormat df, NumberFormat nf, ExportLanguage lang) {
    if (payment.type == PaymentType.electricity && payment.electricityStartReading != null) {
      return [_electricityItem(payment, df, nf, lang)];
    }
    if (payment.type == PaymentType.water && payment.waterStartReading != null) {
      return [_waterItem(payment, df, nf, lang)];
    }
    
    // Default mapping for single types
    return [_XlsLineItem(
      typeLabel: _l(payment.type.name, lang),
      amount: payment.amount,
      detail: payment.description,
    )];
  }

  static _XlsLineItem _electricityItem(Payment p, DateFormat df, NumberFormat nf, ExportLanguage lang) {
    final start = p.electricityStartReading ?? 0;
    final end = p.electricityEndReading ?? 0;
    final usage = end - start;
    final detail = '${_l('meter_reading', lang)} $start → $end kWh (${usage.toStringAsFixed(1)} kWh)\n${_l('billing_cycle', lang)} ${df.format(p.electricityStartDate!)} – ${df.format(p.electricityEndDate!)}';
    return _XlsLineItem(typeLabel: _l('electricity', lang), amount: p.amount, detail: detail);
  }

  static _XlsLineItem _waterItem(Payment p, DateFormat df, NumberFormat nf, ExportLanguage lang) {
    final start = p.waterStartReading ?? 0;
    final end = p.waterEndReading ?? 0;
    final usage = end - start;
    final detail = '${_l('meter_reading', lang)} $start → $end m³ (${usage.toStringAsFixed(1)} m³)\n${_l('billing_cycle', lang)} ${df.format(p.waterStartDate!)} – ${df.format(p.waterEndDate!)}';
    return _XlsLineItem(typeLabel: _l('water', lang), amount: p.amount, detail: detail);
  }
}