// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9LyMiD1EP4PCrG26DzzvphhyFtVDAtiY',
    appId: '1:595994118808:web:4cbc3b57688c6ef7271eed',
    messagingSenderId: '595994118808',
    projectId: 'apartment-management-app-776b9',
    authDomain: 'apartment-management-app-776b9.firebaseapp.com',
    storageBucket: 'apartment-management-app-776b9.firebasestorage.app',
    measurementId: 'G-EY5RPH8TJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlkBPA_LEkfg9Qqd-R6LTdGT__1K3x4X4',
    appId: '1:595994118808:android:f099dea390668bee271eed',
    messagingSenderId: '595994118808',
    projectId: 'apartment-management-app-776b9',
    storageBucket: 'apartment-management-app-776b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9DUl3lM7KSSpxGXMWOmH-fHjujIhYRs',
    appId: '1:595994118808:ios:bf9f0ea4d4a26a69271eed',
    messagingSenderId: '595994118808',
    projectId: 'apartment-management-app-776b9',
    storageBucket: 'apartment-management-app-776b9.firebasestorage.app',
    iosBundleId: 'com.example.apartmentManagementProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc9DUl3lM7KSSpxGXMWOmH-fHjujIhYRs',
    appId: '1:595994118808:ios:bf9f0ea4d4a26a69271eed',
    messagingSenderId: '595994118808',
    projectId: 'apartment-management-app-776b9',
    storageBucket: 'apartment-management-app-776b9.firebasestorage.app',
    iosBundleId: 'com.example.apartmentManagementProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfQZfoKw1O6Eteoj_jSeouEpe7m3aRyAo',
    appId: '1:595994118808:web:5af7c088a203ac12271eed',
    messagingSenderId: '595994118808',
    projectId: 'apartment-management-app-776b9',
    authDomain: 'apartment-management-app-776b9.firebaseapp.com',
    storageBucket: 'apartment-management-app-776b9.firebasestorage.app',
    measurementId: 'G-43LG0962SF',
  );

}